/run/numberOfThreads 8
/run/initialize
/gun/momentumAmp 1 GeV
/gun/position 0 0 0 m
/gun/particle pi+
/run/beamOn 1000
/gun/momentumAmp 1 GeV
/gun/position 0 0 0 m
/gun/particle pi-
/run/beamOn 1000
/gun/momentumAmp 10 GeV
/gun/position 0 0 0 m
/gun/particle e+
/run/beamOn 1000
/gun/momentumAmp 10 GeV
/gun/position 0 0 0 m
/gun/particle e-
/run/beamOn 1000
/gun/momentumAmp 10 GeV
/gun/position 0 0 0 m
/gun/particle mu-
/run/beamOn 1000
